/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alyssa
 */
public class InterestCalculator extends javax.swing.JFrame {

    /**
     * Creates new form InterestCalculator
     */
    public InterestCalculator() {
        initComponents();
        setResultsLabelsNotVisible();
        calcButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainLabel = new javax.swing.JLabel();
        initInvestLabel = new javax.swing.JLabel();
        annualContrLabel = new javax.swing.JLabel();
        monthlyContrLabel = new javax.swing.JLabel();
        beginButton = new javax.swing.JRadioButton();
        endButton = new javax.swing.JRadioButton();
        IRLabel = new javax.swing.JLabel();
        compoundLabel = new javax.swing.JLabel();
        investLenLabel = new javax.swing.JLabel();
        taxRateLabel = new javax.swing.JLabel();
        inflationRateLabel = new javax.swing.JLabel();
        calcButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        midLabel1 = new javax.swing.JLabel();
        midLebel2 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        resultsLabel = new javax.swing.JLabel();
        endBalanceLabel = new javax.swing.JLabel();
        totalPrinLabel = new javax.swing.JLabel();
        totalContrLabel = new javax.swing.JLabel();
        totalInterestLabel = new javax.swing.JLabel();
        interestOfInitLabel = new javax.swing.JLabel();
        interestOfContrLabel = new javax.swing.JLabel();
        buyPowerLabel = new javax.swing.JLabel();
        initInvestField = new javax.swing.JTextField();
        annualContrField = new javax.swing.JTextField();
        monthlyContrField = new javax.swing.JTextField();
        IRField = new javax.swing.JTextField();
        investLenYField = new javax.swing.JTextField();
        taxRateField = new javax.swing.JTextField();
        inflationRateField = new javax.swing.JTextField();
        investLenMField = new javax.swing.JTextField();
        yearsLabel = new javax.swing.JLabel();
        monthsLabel = new javax.swing.JLabel();
        compoundBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainLabel.setText("Interest Calculator");

        initInvestLabel.setText("Initial investment");

        annualContrLabel.setText("Annual contribution");

        monthlyContrLabel.setText("Monthly contribution");

        buttonGroup1.add(beginButton);
        beginButton.setText("beginning");

        buttonGroup1.add(endButton);
        endButton.setText("end");

        IRLabel.setText("Interest rate (%)");

        compoundLabel.setText("Compound");

        investLenLabel.setText("Investment length");

        taxRateLabel.setText("Tax rate (%)");

        inflationRateLabel.setText("Inflation rate (%)");

        calcButton.setText("Calculate");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        midLabel1.setText("Contribute at the");

        midLebel2.setText("of each compounding period");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        resultsLabel.setText("Results");

        endBalanceLabel.setText("Ending balance");

        totalPrinLabel.setText("Total principal");

        totalContrLabel.setText("Total contributions");

        totalInterestLabel.setText("Total interest");

        interestOfInitLabel.setText("Interest of initial investment");

        interestOfContrLabel.setText("Interest of the contributions");

        buyPowerLabel.setText("<html>Buying power of the end\nbalance after inflation\nadjustment");
        buyPowerLabel.setToolTipText("");

        initInvestField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                initInvestFieldFocusLost(evt);
            }
        });
        initInvestField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                initInvestFieldKeyPressed(evt);
            }
        });

        annualContrField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                annualContrFieldFocusLost(evt);
            }
        });
        annualContrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                annualContrFieldKeyPressed(evt);
            }
        });

        monthlyContrField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthlyContrFieldFocusLost(evt);
            }
        });
        monthlyContrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monthlyContrFieldKeyPressed(evt);
            }
        });

        IRField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IRFieldFocusLost(evt);
            }
        });
        IRField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IRFieldKeyPressed(evt);
            }
        });

        investLenYField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                investLenYFieldFocusLost(evt);
            }
        });
        investLenYField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                investLenYFieldKeyPressed(evt);
            }
        });

        taxRateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                taxRateFieldFocusLost(evt);
            }
        });
        taxRateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taxRateFieldKeyPressed(evt);
            }
        });

        inflationRateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inflationRateFieldFocusLost(evt);
            }
        });
        inflationRateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inflationRateFieldKeyPressed(evt);
            }
        });

        investLenMField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                investLenMFieldFocusLost(evt);
            }
        });
        investLenMField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                investLenMFieldKeyPressed(evt);
            }
        });

        yearsLabel.setText("years");

        monthsLabel.setText("months");

        compoundBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "annually", "semiannually", "quarterly", "monthly", "semimonthly", "biweekly", "weekly", "daily", "continuously" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(initInvestLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IRLabel)
                                    .addComponent(compoundLabel)
                                    .addComponent(investLenLabel)
                                    .addComponent(taxRateLabel)
                                    .addComponent(inflationRateLabel))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(compoundBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)
                                        .addComponent(IRField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(inflationRateField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                        .addComponent(taxRateField, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(midLebel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(annualContrLabel)
                                    .addComponent(monthlyContrLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(annualContrField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(initInvestField)
                                    .addComponent(monthlyContrField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(investLenYField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearsLabel)
                                .addGap(5, 5, 5)
                                .addComponent(investLenMField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(calcButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(midLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beginButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endButton)))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(interestOfContrLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(resultsLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(endBalanceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(totalPrinLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(totalContrLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(interestOfInitLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(buyPowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(totalInterestLabel)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainLabel))
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(initInvestLabel)
                            .addComponent(initInvestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(annualContrLabel)
                            .addComponent(annualContrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthlyContrLabel)
                            .addComponent(monthlyContrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endButton)
                            .addComponent(beginButton)
                            .addComponent(midLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(midLebel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IRLabel)
                            .addComponent(IRField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compoundLabel)
                            .addComponent(compoundBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(investLenLabel)
                            .addComponent(investLenYField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(investLenMField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearsLabel)
                            .addComponent(monthsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxRateLabel)
                            .addComponent(taxRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(endBalanceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalPrinLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalContrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalInterestLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(interestOfInitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(interestOfContrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buyPowerLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inflationRateLabel)
                    .addComponent(inflationRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcButton)
                    .addComponent(clearButton))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // function is the "calculator" part
    }//GEN-LAST:event_calcButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        setResultsLabelsNotVisible();
        calcButton.setEnabled(false);
        initInvestField.setText("");
        annualContrField.setText("");
        monthlyContrField.setText("");
        IRField.setText("");
        investLenYField.setText("");
        investLenMField.setText("");
        taxRateField.setText("");
        inflationRateField.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void initInvestFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_initInvestFieldKeyPressed
        // if "enter" key pressed, check if input is valid
        // if all fields have an input, enable calcButton
        if (evt.getKeyCode() == 10) {
            if (initInvestField.getText().strip().compareTo("") != 0) {
               if (! (MainHelper.isValidNumber(initInvestField.getText()))){
                    initInvestField.setText("");
                    initInvestField.requestFocus();
                    calcButton.setEnabled(false);
                    setResultsLabelsNotVisible();
  
                } 
               else {
                    if (initInvestField.getText().strip().compareTo("") == 0){
                    annualContrField.requestFocus();
                    }
                    if (allFieldsHaveValue()) {
                       calcButton.setEnabled(true);
                    }
               }
            }
        }
    }//GEN-LAST:event_initInvestFieldKeyPressed

    private void initInvestFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_initInvestFieldFocusLost
        // checks for valid input
        // if all fields have an input, enable calcButton
        if (initInvestField.getText().strip().compareTo("") != 0) {
            if (! (MainHelper.isValidNumber(initInvestField.getText()))){
                initInvestField.setText("");
                initInvestField.requestFocus();
                calcButton.setEnabled(false);
                setResultsLabelsNotVisible();
            } 
            else {
                if (initInvestField.getText().strip().compareTo("") == 0){
                    annualContrField.requestFocus();
                }
                if (allFieldsHaveValue()) {
                    calcButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_initInvestFieldFocusLost

    private void annualContrFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_annualContrFieldKeyPressed
        // if "enter" key pressed, check if input is valid
        // if all fields have an input, enable calcButton
        if (evt.getKeyCode() == 10) {
            if (annualContrField.getText().strip().compareTo("") != 0) {
               if (! (MainHelper.isValidNumber(annualContrField.getText()))){
                    annualContrField.setText("");
                    annualContrField.requestFocus();
                    calcButton.setEnabled(false);
                    setResultsLabelsNotVisible();
  
                } 
               else {
                    if (annualContrField.getText().strip().compareTo("") == 0){
                    monthlyContrField.requestFocus();
                    }
                    if (allFieldsHaveValue()) {
                       calcButton.setEnabled(true);
                    }
               }
            }
        }
    }//GEN-LAST:event_annualContrFieldKeyPressed

    private void annualContrFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_annualContrFieldFocusLost
        // checks for valid input
        // if all fields have an input, enable calcButton
        if (annualContrField.getText().strip().compareTo("") != 0) {
            if (! (MainHelper.isValidNumber(annualContrField.getText()))){
                annualContrField.setText("");
                annualContrField.requestFocus();
                calcButton.setEnabled(false);
                setResultsLabelsNotVisible();
            } 
            else {
                if (annualContrField.getText().strip().compareTo("") == 0){
                    monthlyContrField.requestFocus();
                }
                if (allFieldsHaveValue()) {
                    calcButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_annualContrFieldFocusLost

    private void monthlyContrFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthlyContrFieldKeyPressed
        // if "enter" key pressed, check if input is valid
        // if all fields have an input, enable calcButton
        if (evt.getKeyCode() == 10) {
            if (monthlyContrField.getText().strip().compareTo("") != 0) {
               if (! (MainHelper.isValidNumber(monthlyContrField.getText()))){
                    monthlyContrField.setText("");
                    monthlyContrField.requestFocus();
                    calcButton.setEnabled(false);
                    setResultsLabelsNotVisible();
  
                } 
               else {
                    if (monthlyContrField.getText().strip().compareTo("") == 0){
                    IRField.requestFocus();
                    }
                    if (allFieldsHaveValue()) {
                       calcButton.setEnabled(true);
                    }
               }
            }
        }
    }//GEN-LAST:event_monthlyContrFieldKeyPressed

    private void monthlyContrFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthlyContrFieldFocusLost
        // checks for valid input
        // if all fields have an input, enable calcButton
        if (monthlyContrField.getText().strip().compareTo("") != 0) {
            if (! (MainHelper.isValidNumber(monthlyContrField.getText()))){
                monthlyContrField.setText("");
                monthlyContrField.requestFocus();
                calcButton.setEnabled(false);
                setResultsLabelsNotVisible();
            } 
            else {
                if (monthlyContrField.getText().strip().compareTo("") == 0){
                    IRField.requestFocus();
                }
                if (allFieldsHaveValue()) {
                    calcButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_monthlyContrFieldFocusLost

    private void IRFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IRFieldKeyPressed
        // if "enter" key pressed, check if input is valid
        // if all fields have an input, enable calcButton
        if (evt.getKeyCode() == 10) {
            if (IRField.getText().strip().compareTo("") != 0) {
               if (! (MainHelper.isValidNumber(IRField.getText()))){
                    IRField.setText("");
                    IRField.requestFocus();
                    calcButton.setEnabled(false);
                    setResultsLabelsNotVisible();
  
                } 
               else {
                    if (IRField.getText().strip().compareTo("") == 0){
                    investLenYField.requestFocus();
                    }
                    if (allFieldsHaveValue()) {
                       calcButton.setEnabled(true);
                    }
               }
            }
        }
    }//GEN-LAST:event_IRFieldKeyPressed

    private void IRFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IRFieldFocusLost
        // checks for valid input
        // if all fields have an input, enable calcButton
        if (IRField.getText().strip().compareTo("") != 0) {
            if (! (MainHelper.isValidNumber(IRField.getText()))){
                IRField.setText("");
                IRField.requestFocus();
                calcButton.setEnabled(false);
                setResultsLabelsNotVisible();
            } 
            else {
                if (IRField.getText().strip().compareTo("") == 0){
                    investLenYField.requestFocus();
                }
                if (allFieldsHaveValue()) {
                    calcButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_IRFieldFocusLost

    private void investLenYFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_investLenYFieldKeyPressed
        // if "enter" key pressed, check if input is valid
        // if all fields have an input, enable calcButton
        if (evt.getKeyCode() == 10) {
            if (investLenYField.getText().strip().compareTo("") != 0) {
               if (! (MainHelper.isValidNumber(investLenYField.getText()))){
                    investLenYField.setText("");
                    investLenYField.requestFocus();
                    calcButton.setEnabled(false);
                    setResultsLabelsNotVisible();
  
                } 
               else {
                    if (investLenYField.getText().strip().compareTo("") == 0){
                    investLenMField.requestFocus();
                    }
                    if (allFieldsHaveValue()) {
                       calcButton.setEnabled(true);
                    }
               }
            }
        }
    }//GEN-LAST:event_investLenYFieldKeyPressed

    private void investLenYFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_investLenYFieldFocusLost
        // checks for valid input
        // if all fields have an input, enable calcButton
        if (investLenYField.getText().strip().compareTo("") != 0) {
            if (! (MainHelper.isValidNumber(investLenYField.getText()))){
                investLenYField.setText("");
                investLenYField.requestFocus();
                calcButton.setEnabled(false);
                setResultsLabelsNotVisible();
            } 
            else {
                if (investLenYField.getText().strip().compareTo("") == 0){
                    investLenMField.requestFocus();
                }
                if (allFieldsHaveValue()) {
                    calcButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_investLenYFieldFocusLost

    private void investLenMFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_investLenMFieldKeyPressed
        // if "enter" key pressed, check if input is valid
        // if all fields have an input, enable calcButton
        if (evt.getKeyCode() == 10) {
            if (investLenMField.getText().strip().compareTo("") != 0) {
               if (! (MainHelper.isValidNumber(investLenMField.getText()))){
                    investLenMField.setText("");
                    investLenMField.requestFocus();
                    calcButton.setEnabled(false);
                    setResultsLabelsNotVisible();
  
                } 
               else {
                    if (investLenMField.getText().strip().compareTo("") == 0){
                    taxRateField.requestFocus();
                    }
                    if (allFieldsHaveValue()) {
                       calcButton.setEnabled(true);
                    }
               }
            }
        }
    }//GEN-LAST:event_investLenMFieldKeyPressed

    private void investLenMFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_investLenMFieldFocusLost
        // checks for valid input
        // if all fields have an input, enable calcButton
        if (investLenMField.getText().strip().compareTo("") != 0) {
            if (! (MainHelper.isValidNumber(investLenMField.getText()))){
                investLenMField.setText("");
                investLenMField.requestFocus();
                calcButton.setEnabled(false);
                setResultsLabelsNotVisible();
            } 
            else {
                if (investLenMField.getText().strip().compareTo("") == 0){
                    taxRateField.requestFocus();
                }
                if (allFieldsHaveValue()) {
                    calcButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_investLenMFieldFocusLost

    private void taxRateFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taxRateFieldKeyPressed
        // if "enter" key pressed, check if input is valid
        // if all fields have an input, enable calcButton
        if (evt.getKeyCode() == 10) {
            if (taxRateField.getText().strip().compareTo("") != 0) {
               if (! (MainHelper.isValidNumber(taxRateField.getText()))){
                    taxRateField.setText("");
                    taxRateField.requestFocus();
                    calcButton.setEnabled(false);
                    setResultsLabelsNotVisible();
  
                } 
               else {
                    if (taxRateField.getText().strip().compareTo("") == 0){
                    inflationRateField.requestFocus();
                    }
                    if (allFieldsHaveValue()) {
                       calcButton.setEnabled(true);
                    }
               }
            }
        }
    }//GEN-LAST:event_taxRateFieldKeyPressed

    private void taxRateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taxRateFieldFocusLost
        // checks for valid input
        // if all fields have an input, enable calcButton
        if (taxRateField.getText().strip().compareTo("") != 0) {
            if (! (MainHelper.isValidNumber(taxRateField.getText()))){
                taxRateField.setText("");
                taxRateField.requestFocus();
                calcButton.setEnabled(false);
                setResultsLabelsNotVisible();
            } 
            else {
                if (taxRateField.getText().strip().compareTo("") == 0){
                    inflationRateField.requestFocus();
                }
                if (allFieldsHaveValue()) {
                    calcButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_taxRateFieldFocusLost

    private void inflationRateFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inflationRateFieldKeyPressed
        // if "enter" key pressed, check if input is valid
        // if all fields have an input, enable calcButton
        if (evt.getKeyCode() == 10) {
            if (inflationRateField.getText().strip().compareTo("") != 0) {
               if (! (MainHelper.isValidNumber(inflationRateField.getText()))){
                    inflationRateField.setText("");
                    inflationRateField.requestFocus();
                    calcButton.setEnabled(false);
                    setResultsLabelsNotVisible();
  
                } 
               else {
                    if (allFieldsHaveValue()) {
                       calcButton.setEnabled(true);
                    }
               }
            }
        }
    }//GEN-LAST:event_inflationRateFieldKeyPressed

    private void inflationRateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inflationRateFieldFocusLost
        // checks for valid input
        // if all fields have an input, enable calcButton
        if (inflationRateField.getText().strip().compareTo("") != 0) {
            if (! (MainHelper.isValidNumber(inflationRateField.getText()))){
                inflationRateField.setText("");
                inflationRateField.requestFocus();
                calcButton.setEnabled(false);
                setResultsLabelsNotVisible();
            } 
            else {
                if (allFieldsHaveValue()) {
                    calcButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_inflationRateFieldFocusLost

    private void setResultsLabelsNotVisible() {
        resultsLabel.setVisible(false);
        endBalanceLabel.setVisible(false);
        totalPrinLabel.setVisible(false);
        totalContrLabel.setVisible(false);
        totalInterestLabel.setVisible(false);
        interestOfInitLabel.setVisible(false);
        interestOfContrLabel.setVisible(false);
        buyPowerLabel.setVisible(false);
    }
    
    private boolean allFieldsHaveValue() {
        int ii = initInvestField.getText().strip().compareTo("");
        int ac = annualContrField.getText().strip().compareTo("");
        int mc = monthlyContrField.getText().strip().compareTo("");
        int ir = IRField.getText().strip().compareTo("");
        int ilY = investLenYField.getText().strip().compareTo("");
        int ilM = investLenMField.getText().strip().compareTo("");
        int tr = taxRateField.getText().strip().compareTo("");
        int inflationr = inflationRateField.getText().strip().compareTo("");
        return ii != 0 && ac != 0 && mc != 0 && ir != 0 && ilY != 0 && ilM != 0 
                && tr != 0 && inflationr != 0 && 
                (beginButton.isSelected() || endButton.isSelected());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterestCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterestCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterestCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterestCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterestCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IRField;
    private javax.swing.JLabel IRLabel;
    private javax.swing.JTextField annualContrField;
    private javax.swing.JLabel annualContrLabel;
    private javax.swing.JRadioButton beginButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel buyPowerLabel;
    private javax.swing.JButton calcButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> compoundBox;
    private javax.swing.JLabel compoundLabel;
    private javax.swing.JLabel endBalanceLabel;
    private javax.swing.JRadioButton endButton;
    private javax.swing.JTextField inflationRateField;
    private javax.swing.JLabel inflationRateLabel;
    private javax.swing.JTextField initInvestField;
    private javax.swing.JLabel initInvestLabel;
    private javax.swing.JLabel interestOfContrLabel;
    private javax.swing.JLabel interestOfInitLabel;
    private javax.swing.JLabel investLenLabel;
    private javax.swing.JTextField investLenMField;
    private javax.swing.JTextField investLenYField;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel midLabel1;
    private javax.swing.JLabel midLebel2;
    private javax.swing.JTextField monthlyContrField;
    private javax.swing.JLabel monthlyContrLabel;
    private javax.swing.JLabel monthsLabel;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JTextField taxRateField;
    private javax.swing.JLabel taxRateLabel;
    private javax.swing.JLabel totalContrLabel;
    private javax.swing.JLabel totalInterestLabel;
    private javax.swing.JLabel totalPrinLabel;
    private javax.swing.JLabel yearsLabel;
    // End of variables declaration//GEN-END:variables
}
